# Generated by Django 3.1.7 on 2021-04-04 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Department')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Datetime')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Department')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Day')),
                ('department', models.ManyToManyField(to='namelist.Department', verbose_name='Department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='namelist.projectteam', verbose_name='ProjectName')),
            ],
        ),
    ]
